### ISSUE TITLE
Issues reported by C2C

### ISSUE THREAD

**Issue by clu2xlu** [CentaurusInfra/mizar#500]
- Vanilla Kubernetes deployment: 
           - deploy.mizar.components.yaml only works for 20.04 Ubuntu. Does not work well in 18.06 Ubuntu. 
           - With Ubuntu 18.06, mizarcni.conf is not generated. Bouncers and dividers are not getting created. 
           - privilege mode is necessary for single yaml deployment as files are not generated if kept false.
- In our user-guide, https://github.com/CentaurusInfra/mizar/blob/dev-next/docs/user/getting_started.md, it's using deploy.mizar.components.yaml. However, it's still using 0.7. Shall we update to 0.8 version? 

- Python 3.7 did not work in arktos-mizar integration. Already informed C2C we will be working on this after this release

**Comment by vinaykul** [comment]
@clu2xlu We had a meeting with C2C this morning and discussed them using 0.8 with Ubuntu 18.04.05 going forward as it fixes many issues including the regression caused by their earlier commit, and we have tested it at our end in AWS as well as locally with Fusion VMs.

They are seeing one issue in their Ubuntu 18.04 setup that we don't see and they will file a separate issue for that. Please work with them to get a local repro, and investigate the issue with them. Thanks

**Comment by vinaykul** [comment]
I have been driving this effort with C2C, and they are working on fixing these issues. deploy.mizar.yaml deprecates the old yaml and has been working well.
